### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by raphaelbp12** [poesimulator/poesimulator.github.io#1]
Will you open the code / project? I want to contribute!

Thank you for all your work, and for assets! You did an amazing job!

**Comment by LostRuins** [comment]
Hi! I'm glad you liked it. As I mentioned on Reddit before, I do use some paid Unity plugins that prevent me from releasing the source code for this project. That said, the art assets used are freely available at https://poesimulator.github.io/Extra/ArtAssets.zip 

Cheers!
